### ISSUE TITLE
Unable to launch CKF3

### ISSUE THREAD

**Issue by brokenphilip** [CKFDevPowered/CKF3Alpha#2] opened 2019-10-14 19:50 UTC
![image](https://user-images.githubusercontent.com/13336890/66777728-fb17f800-eec9-11e9-8d8a-207e2cab3908.png)

Crashes both steam (newest, error above) & non-steam (Warzone, no errors - just closes) Half-Life versions on Windows 10 1809 64bit.

Here's the minidump file the non-steam version generated, if it helps:
[mdmp.zip](https://github.com/CKFDevPowered/CKF3Alpha/files/3726165/mdmp.zip)

**Comment by hzqst** [comment] 2019-10-21 04:38
see https://github.com/CKFDevPowered/CKF3Alpha/blob/deddd3c2d4c1532620dd01631eb1e733445d07bb/src_ckf/Audio/snd_hook.cpp#L29

You can find new sig with hex-ray IDA :
decompile hw.dll with IDA
search for xref to text "S_StartDynamicSound: %s volume > 255"
then you can find S_LoadSound (the screenshot is for engine 6153, you have to find S_LoadSound for your 8308 engine, in the same way ).
![sss](https://user-images.githubusercontent.com/12287588/67177056-559be180-f3ff-11e9-9d80-70d57bd0c44c.png)
![ssss](https://user-images.githubusercontent.com/12287588/67177058-56cd0e80-f3ff-11e9-9e39-061d46ae7a5b.png)
![sssss](https://user-images.githubusercontent.com/12287588/67177110-9693f600-f3ff-11e9-9066-ed23e3385dda.png)

**Comment by selimnahimi** [comment] 2019-10-29 13:45
I have done the steps described above, however, even after replacing the hex code and compiling successfully, I get a different error message. Not really sure what this one is referring to.
![Error message](https://user-images.githubusercontent.com/21970287/67772635-b27c4500-fa5a-11e9-9314-f49a5dd0ced6.png)

After some digging I figured it's referring to this in **gl_hooks.cpp**, although I have absolutely no idea where to find the hex code for it.

`#define R_STUDIORENDERFINAL_SIG_NEW "\x55\x8B\xEC\x51\x6A\x00\x6A\x00\xC7\x05\x2A\x2A\x2A\x2A\x2A\x2A\x2A\x2A\xC7\x05\x2A\x2A\x2A\x2A\x2A\x2A\x2A\x2A\xE8"`

**Comment by yuxuanchiadm** [comment] 2019-11-26 22:29
Fixed 3 crashes with https://github.com/CKFDevPowered/CKF3Alpha/commit/290a1db3be70508e0780e80eb4e23b084d554f63. But there still other crashes.

**Comment by yuxuanchiadm** [comment] 2019-11-26 22:32
@HUNcamper Can you check the latest version? "Could not found: SOMETHING" error should be fixed.

**Comment by yuxuanchiadm** [comment] 2019-11-27 02:49
I have fixed all crashes. Please check https://github.com/CKFDevPowered/CKF3Alpha/commit/9bb42564c78ad99588009a0d2a1d4b7f01f2907f.

**Comment by selimnahimi** [comment] 2019-12-07 14:47
@yuxuanchiadm 

Even after:
- Reinstalling Half-Life
- Making a clean install of CKF3
- Replacing the DLLs with the new compiled DLLs (which have the newest commits)

The game does launch but crashes upon loading the main menu without any error.
It gets this far, which is further than before:
![kép](https://user-images.githubusercontent.com/21970287/70376705-191f3900-190c-11ea-8702-c0ee4b0ca4a8.png)

**Comment by yuxuanchiadm** [comment] 2019-12-12 06:20
@HUNcamper Need more information for further investigation. Minidump upon crashes will help.

**Comment by selimnahimi** [comment] 2019-12-12 11:28
How can I get Half-Life to generate a minidump?

**Comment by hzqst** [comment] 2019-12-12 11:36
check C:\Program Files (x86)\Steam\dumps\ and you will minidump files.

**Comment by selimnahimi** [comment] 2019-12-12 11:39
Here it is:
[crash_hl.exe_20191212123724_1.dmp.zip](https://github.com/CKFDevPowered/CKF3Alpha/files/3955510/crash_hl.exe_20191212123724_1.dmp.zip)

**Comment by selimnahimi** [comment] 2019-12-12 11:45
Another weird occurence is when I launch the game in cmd (not through Steam) like this:
`hl.exe -game ckf3`
The following happens:
https://www.youtube.com/watch?v=DCb83uDuA0c

Can only navigate the main menu using the arrow keys, and it's obvious that in this state the game is using the CS base to run.
Upon loading a map I can't do anything because the team/class selection menu instantly closes.

When launching using ckf3.exe, it gets to the loading screen but crashes as mentioned before.
I have a feeling it has to do something with the exe.

**Comment by brokenphilip** [comment] 2019-12-12 12:00
> Another weird occurence is when I launch the game in cmd (not through Steam) like this:
> `hl.exe -game ckf3`
> The following happens:
> https://www.youtube.com/watch?v=DCb83uDuA0c
> 
> Can only navigate the main menu using the arrow keys, and it's obvious that in this state the game is using the CS base to run.
> Upon loading a map I can't do anything because the team/class selection menu instantly closes.
> 
> When launching using ckf3.exe, it gets to the loading screen but crashes as mentioned before.
> I have a feeling it has to do something with the exe.

I remember having the exact same issue a while ago (the crash one as well), even before Half-Life got updated on Steam.

**Comment by yuxuanchiadm** [comment] 2019-12-12 12:28
> Another weird occurence is when I launch the game in cmd (not through Steam) like this:
> `hl.exe -game ckf3`
> The following happens:
> https://www.youtube.com/watch?v=DCb83uDuA0c
> 
> Can only navigate the main menu using the arrow keys, and it's obvious that in this state the game is using the CS base to run.
> Upon loading a map I can't do anything because the team/class selection menu instantly closes.
> 
> When launching using ckf3.exe, it gets to the loading screen but crashes as mentioned before.
> I have a feeling it has to do something with the exe.

Game should launch with the `-steam` flag like:
`hl.exe -steam -game ckf3`

**Comment by selimnahimi** [comment] 2019-12-12 12:31
OK! I don't know what was wrong with my installation but after completely getting rid of the Half-Life folder from Steam and re-installing everything, then replacing the DLLs, it works! Hooray, something was wrong on my end. You can close the issue.

![kép](https://user-images.githubusercontent.com/21970287/70712237-9cada100-1ce3-11ea-8fe3-9b83a6e27f95.png)

**Comment by yuxuanchiadm** [comment] 2019-12-12 12:35
> OK! I don't know what was wrong with my installation but after completely getting rid of the Half-Life folder from Steam and re-installing everything, then replacing the DLLs, it works! Hooray, something was wrong on my end. You can close the issue.
> 
> ![kép](https://user-images.githubusercontent.com/21970287/70712237-9cada100-1ce3-11ea-8fe3-9b83a6e27f95.png)

Then have fun! We got KOTH mode and some new maps recently😄

**Comment by selimnahimi** [comment] 2019-12-12 13:02
> Then have fun! We got KOTH mode and some new maps recently😄

Nice! Will you release the maps later on or are they available somewhere?

**Comment by yuxuanchiadm** [comment] 2019-12-12 13:16
> > Then have fun! We got KOTH mode and some new maps recently😄
> 
> Nice! Will you release the maps later on or are they available somewhere?

Check latest commit https://github.com/CKFDevPowered/CKF3Alpha/commit/7884e93fffd1d67bc2bceffd2f73075ea16e3f52
All currently available maps has being uploaded.

**Comment by brokenphilip** [comment] 2019-12-12 14:13
> OK! I don't know what was wrong with my installation but after completely getting rid of the Half-Life folder from Steam and re-installing everything, then replacing the DLLs, it works! Hooray, something was wrong on my end. You can close the issue.
> 
> ![kép](https://user-images.githubusercontent.com/21970287/70712237-9cada100-1ce3-11ea-8fe3-9b83a6e27f95.png)

Didn't work for me... Even after building & copying the DLLs after completely wiping my Half-Life folder from Steam I'm still having the same issue like in the video you sent. Tested both with `ckf3.exe` (not crashing for me) as well as `hl.exe -steam -game ckf3`, same results.

**Comment by yuxuanchiadm** [comment] 2019-12-12 14:24
> > OK! I don't know what was wrong with my installation but after completely getting rid of the Half-Life folder from Steam and re-installing everything, then replacing the DLLs, it works! Hooray, something was wrong on my end. You can close the issue.
> > ![kép](https://user-images.githubusercontent.com/21970287/70712237-9cada100-1ce3-11ea-8fe3-9b83a6e27f95.png)
> 
> Didn't work for me... Even after building & copying the DLLs after completely wiping my Half-Life folder from Steam I'm still having the same issue like in the video you sent. Tested both with `ckf3.exe` (not crashing for me) as well as `hl.exe -steam -game ckf3`, same results.

Can you check if dlls is in correct location:
```
Half-Life\ckf3\Audio.dll
Half-Life\ckf3\CaptionMod.dll
Half-Life\ckf3\MetaHook.dll
Half-Life\ckf3\Renderer.dll
Half-Life\ckf3\dlls\mp.dll
Half-Life\ckf3\cl_dlls\client.dll
Half-Life\ckf3\MetaHook\CSBTE.dll
```

**Comment by brokenphilip** [comment] 2019-12-12 15:23
I seem to be missing
`Half-Life\ckf3\CaptionMod.dll`
`Half-Life\ckf3\Renderer.dll`
`Half-Life\ckf3\MetaHook\CSBTE.dll`

Any possible reasons why? While compiling I got a lot of errors saying: `Cannot open include file: 'gl/glext.h': No such file or directory`, could be that

**Comment by hzqst** [comment] 2019-12-12 15:35
https://github.com/KhronosGroup/OpenGL-Registry/blob/master/api/GL/glext.h

**Comment by brokenphilip** [comment] 2019-12-12 16:12
After downloading it and placing it in  `.\src\Interface\gl` I was also missing `KHR/khrplatform.h`, which I downloaded from https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h

Then the build was successful and without errors (I checked and all the DLL files were in place) but when I launch the game I see the background for a split-second and then the game exits with this pop-up:
![image](https://user-images.githubusercontent.com/13336890/70727543-22d7e080-1d00-11ea-9fec-a28288861f46.png)

**Comment by yuxuanchiadm** [comment] 2019-12-13 05:41
> After downloading it and placing it in `.\src\Interface\gl` I was also missing `KHR/khrplatform.h`, which I downloaded from https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h
> 
> Then the build was successful and without errors (I checked and all the DLL files were in place) but when I launch the game I see the background for a split-second and then the game exits with this pop-up:
> ![image](https://user-images.githubusercontent.com/13336890/70727543-22d7e080-1d00-11ea-9fec-a28288861f46.png)

This happens when CaptionMod cannot find Renderer. You could check Renderer is compiled correctly and loaded correctly.

**Comment by brokenphilip** [comment] 2019-12-16 22:44
After debugging I had noticed that the Renderer.dll loads, then shortly after unloads itself, as shown in the debug logs VS gave me here: https://pastebin.com/83n3nCr4

If it helps, I've noticed that the messagebox sent by `CaptionMod\engfuncs.cpp` upon game launch is the first one (hRenderer): 
![image](https://user-images.githubusercontent.com/13336890/70949150-5fd40800-205d-11ea-94bf-6d955753d09d.png)

At this point I feel like I reached a dead-end, I'm pretty new to compiling projects of this size so any tips would be appreciated :)

**Comment by yuxuanchiadm** [comment] 2019-12-17 07:33
Place breakpoint at `.\src\Renderer.cpp:72`. Check the value of `g_hRenderer` returned by `Sys_LoadModule`. Use `GetLastError` to get errorcode if it returns `NULL`.

**Comment by brokenphilip** [comment] 2019-12-27 22:09
I just got the notification, apologies for my inactivity.

I've been trying to find solutions for the past couple of days but with no results. The only thing that I found out from the debugger is that `g_hRenderer` indeed returns NULL with a `GetLastError()` result of 126, "The specified module could not be found."

I have checked the value of `filepath` as well and it returns "ckf3/Renderer.dll" which is where the file is indeed located from the executable's perspective.

I have tried running both executables as admin, setting up the folder and file permissions as well as even copying the dll to several places where it might get found without any luck.

**Comment by yuxuanchiadm** [comment] 2019-12-27 22:38
@brokenphilip This may caused by missing DLL dependencies for `Renderer.dll`. You can use utility like "Dependency Walker" to find out which is missing. But I think probably it is "FreeImage.dll". You can try download and install it here: http://freeimage.sourceforge.net/download.html

**Comment by brokenphilip** [comment] 2019-12-28 00:15
I have used the utility and I was indeed only missing FreeImage. After building the FreeImage project and moving the dll to the Half-Life folder the game launched and after playing for a few minutes worked just fine. Thank you so much for helping with my issue! :)

**Closed as completed** 2019-12-28 00:57 UTC
Labels: priority:blocker, category:crash
